In [1]:
import numpy as np

## 多維陣列的索引存取

### 索引物件

In [2]:
a = np.arange(3 * 4 * 5).reshape(3, 4, 5)
lidx = [[0], [1]]
aidx = np.array(lidx)
%C a[lidx]; a[aidx]

     a[lidx]                a[aidx]          
-----------------  --------------------------
[[5, 6, 7, 8, 9]]  [[[[ 0,  1,  2,  3,  4],  
                      [ 5,  6,  7,  8,  9],  
                      [10, 11, 12, 13, 14],  
                      [15, 16, 17, 18, 19]]],
                                             
                                             
                    [[[20, 21, 22, 23, 24],  
                      [25, 26, 27, 28, 29],  
                      [30, 31, 32, 33, 34],  
                      [35, 36, 37, 38, 39]]]]


In [3]:
%C a[tuple(lidx)]; a[aidx,:,:]

  a[tuple(lidx)]          a[aidx,:,:]        
-----------------  --------------------------
[[5, 6, 7, 8, 9]]  [[[[ 0,  1,  2,  3,  4],  
                      [ 5,  6,  7,  8,  9],  
                      [10, 11, 12, 13, 14],  
                      [15, 16, 17, 18, 19]]],
                                             
                                             
                    [[[20, 21, 22, 23, 24],  
                      [25, 26, 27, 28, 29],  
                      [30, 31, 32, 33, 34],  
                      [35, 36, 37, 38, 39]]]]


### 整數群組作為索引

> **TIP**

> 若只需要沿著指定軸透過整數群組取得元素，可以使用`numpy.take()`函數，其運算速度比整數群組的索引運算略快，並且支援索引越界處理。

In [4]:
i0 = np.array([[1, 2, 1], [0, 1, 0]])
i1 = np.array([[[0]], [[1]]])
i2 = np.array([[[2, 3, 2]]])
b = a[i0, i1, i2]
b

array([[[22, 43, 22],
        [ 2, 23,  2]],

       [[27, 48, 27],
        [ 7, 28,  7]]])

In [11]:
b.shape

(2, 2, 3)

In [5]:
ind0, ind1, ind2 = np.broadcast_arrays(i0, i1, i2)
%C ind0; ind1; ind2

     ind0           ind1           ind2    
-------------  -------------  -------------
[[[1, 2, 1],   [[[0, 0, 0],   [[[2, 3, 2], 
  [0, 1, 0]],    [0, 0, 0]],    [2, 3, 2]],
                                           
 [[1, 2, 1],    [[1, 1, 1],    [[2, 3, 2], 
  [0, 1, 0]]]    [1, 1, 1]]]    [2, 3, 2]]]


In [7]:
i, j, k = 0, 1, 2
print b[i, j, k], a[ind0[i, j, k], ind1[i, j, k], ind2[i, j, k]]

i, j, k = 1, 1, 1
print b[i, j, k], a[ind0[i, j, k], ind1[i, j, k], ind2[i, j, k]]

2 2
28 28


In [8]:
c = a[1:3, i0, i1]
c.shape

(2, 2, 2, 3)

In [9]:
ind0, ind1 = np.broadcast_arrays(i0, i1)
ind0.shape

(2, 2, 3)

In [11]:
i, j, k = 1, 1, 2
print c[:, i, j, k]
print a[1:3, ind0[i, j, k], ind1[i, j, k]]  # 和c[:,i,j,k]的值相同

[21 41]
[21 41]


In [12]:
d = a[i0, :, i1]
d.shape

(2, 2, 3, 4)

In [13]:
i, j, k = 1, 1, 2
%C d[i,j,k,:]; a[ind0[i,j,k],:,ind1[i,j,k]]

   d[i,j,k,:]     a[ind0[i,j,k],:,ind1[i,j,k]]
----------------  ----------------------------
[ 1,  6, 11, 16]  [ 1,  6, 11, 16]            


### 一個復雜的實例

> **LINK**

> http://mail.scipy.org/pipermail/numpy-discussion/2008-July/035764.html

> NumPy信件清單中的原文連結

In [5]:
#%hide
%exec_python -m scpy2.numpy.array_index_demo

In [2]:
I, J, K, L = 6, 7, 8, 3
_, _, v = np.mgrid[:I, :J, :K]
idx = np.random.randint(0, K - L, size=(I, J))

In [4]:
idx_k = idx[:, :, None] + np.arange(3)
idx_k.shape

(6, 7, 3)

In [16]:
idx_i, idx_j, _ = np.ogrid[:I, :J, :K]

In [17]:
r = v[idx_i, idx_j, idx_k]    
i, j = 2, 3  # 驗證結果，讀者可以將之修改為使用循環驗證所有的元素
%C r[i,j,:]; v[i,j,idx[i,j]:idx[i,j]+L]

 r[i,j,:]  v[i,j,idx[i,j]:idx[i,j]+L]
---------  --------------------------
[0, 1, 2]  [0, 1, 2]                 


### 布爾陣列作索引

> **TIP**

> 若只需要沿著指定軸透過布爾陣列取得元素，可以使用`numpy.compress()`函數。

In [18]:
b1 = np.array([True, False, True, False])
np.nonzero(b1)

(array([0, 2]),)

In [19]:
b2 = np.array([[True, False, True], [True, False, False]])
np.nonzero(b2)

(array([0, 0, 1]), array([0, 2, 0]))

In [20]:
a = np.arange(3 * 4 * 5).reshape(3, 4, 5)
%C a[b2]; a[np.nonzero(b2)]

        a[b2]             a[np.nonzero(b2)]   
----------------------  ----------------------
[[ 0,  1,  2,  3,  4],  [[ 0,  1,  2,  3,  4],
 [10, 11, 12, 13, 14],   [10, 11, 12, 13, 14],
 [20, 21, 22, 23, 24]]   [20, 21, 22, 23, 24]]


In [21]:
%C a[1:3, b2]; a[1:3, np.nonzero(b2)[0], np.nonzero(b2)[1]]

  a[1:3, b2]    a[1:3, np.nonzero(b2)[0], np.nonzero(b2)[1]]
--------------  --------------------------------------------
[[20, 22, 25],  [[20, 22, 25],                              
 [40, 42, 45]]   [40, 42, 45]]                              
