In [1]:
# -*- coding:utf-8 -*-

import numpy as np

### 2.2.1  一元函數

In [2]:
print(np.abs([-3,-2,5])) 

[3 2 5]


### 2.2.2  二元函數

In [3]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
print(b-a)
print(a*b)
print(b/a)
print(b//a)
print(b%a)

[5 7 9]
[3 3 3]
[ 4 10 18]
[4.  2.5 2. ]
[4 2 2]
[0 1 0]


In [4]:
a = np.array([1,2,3])
b = np.array([1,3,5])
print(a<b)
print(a==b)

[False  True  True]
[ True False False]


### 2.2.3  廣播

In [5]:
a = np.array([1,2,3])
print(a-1)

[0 1 2]


In [6]:
a=np.array([[1,1],[2,2]])
print(a)

[[1 1]
 [2 2]]


In [7]:
b=np.array([1,2])
print("shape", b.shape, a+b)

shape (2,) [[2 3]
 [3 4]]


In [8]:
c=np.array([[1],[2]]) 
print("shape", c.shape, a+c)

shape (2, 1) [[2 2]
 [4 4]]


### 2.2.4  自定義ufunc

In [9]:
def my_ufunc(x, low, high):
    if x < low:
        return -1
    elif x > high:
        return 1
    else:
        return 0
my_ufunci = np.frompyfunc(my_ufunc, 3, 1) 

In [10]:
x = np.arange(1,10,1)
y2 = my_ufunci(x, 3, 6)
print(x)
print(y2)

[1 2 3 4 5 6 7 8 9]
[-1 -1 0 0 0 0 1 1 1]
