In [1]:
#chap6-01a
import numpy as np
print("==Test1==")
#1維陣列array,填入等差數列值0~29
a = np.arange(30)
print(a)
print(a[0])
print(a[29])
print("==Test2==")
#1維陣列array,填入等差數列值10,15,20,25(首項10,公差5,末項<30)
a1 = np.arange(10, 30, 5)
print(a1)
print("==Test3==")
#1維陣列array,填入等差數列值0~2產生等差數列9項, 公差2/(9-1)=0.25
a2 = np.linspace(0, 2, 9)
print(a2) 
print("==Test4==")
#2維陣列array,填入等差數列值
b = np.arange(30).reshape(6,5)
print(b)
print(b[0][0])
print(b[5][4])
print("==Test5==")
#3維陣列array,填入等差數列值
c = np.arange(30).reshape(3,2,5)
print(c)
print(c[0][0][0])
print(c[1][1][4])
print(c[2][1][4])
print("==Test6==")
#1維陣列array,填入自訂值
d = np.array([2,3,4])
print(d)
#2維陣列array,填入自訂值
e = np.array([[7, 2, 3], [4, 5, 6]])
print(e)
#3維陣列array,填入自訂值
f = np.array([[[9, 2], [3, 4]],
        [[5, 6], [7, 8]]])
print(f[0][0][0])
print(f[1][1][1])
print("==Test7==")
#1維陣列array,填入0或1
g = np.zeros(6)
print(g)
g1 = np.ones(6)
print(g1)
#2維陣列array,填入0或1
h = np.zeros((2, 3))
print(h)
h1 = np.ones((2, 3))
print(h1)
#3維陣列array,填入0或1
i = np.zeros((2, 2, 2))
print(i)
i1 = np.ones((2, 2, 2))
print(i1)

==Test1==
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
0
29
==Test2==
[10 15 20 25]
==Test3==
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
==Test4==
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
0
29
==Test5==
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]
0
19
29
==Test6==
[2 3 4]
[[7 2 3]
 [4 5 6]]
9
8
==Test7==
[0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


In [2]:
#chap6-01b
from numpy import arange as npar
from numpy import array as npa
from numpy import linspace as npl
from numpy import ones as np1
from numpy import zeros as np0
print("==Test1==")
#1維陣列array,填入等差數列值0~29
a = npar(30)
print(a)
print(a[0])
print(a[29])
print("==Test2==")
#1維陣列array,填入等差數列值10,15,20,25(首項10,公差5,末項<30)
a1 = npar(10, 30, 5)
print(a1)
print("==Test3==")
#1維陣列array,填入等差數列值0~2產生等差數列9項, 公差2/(9-1)=0.25
a2 = npl(0, 2, 9)
print(a2) 
print("==Test4==")
#2維陣列array,填入等差數列值
b = npar(30).reshape(6,5)
print(b)
print(b[0][0])
print(b[5][4])
print("==Test5==")
#3維陣列array,填入等差數列值
c = npar(30).reshape(3,2,5)
print(c)
print(c[0][0][0])
print(c[1][1][4])
print(c[2][1][4])
print("==Test6==")
#1維陣列array,填入自訂值
d = npa([2,3,4])
print(d)
#2維陣列array,填入自訂值
e = npa([[7, 2, 3], [4, 5, 6]])
print(e)
#3維陣列array,填入自訂值
f = npa([[[9, 2], [3, 4]],
        [[5, 6], [7, 8]]])
print(f[0][0][0])
print(f[1][1][1])
print("==Test7==")
#1維陣列array,填入0或1
g = np0(6)
print(g)
g1 = np1(6)
print(g1)
#2維陣列array,填入0或1
h = np0((2, 3))
print(h)
h1 = np1((2, 3))
print(h1)
#3維陣列array,填入0或1
i = np0((2, 2, 2))
print(i)
i1 = np1((2, 2, 2))
print(i1)

==Test1==
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
0
29
==Test2==
[10 15 20 25]
==Test3==
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
==Test4==
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
0
29
==Test5==
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]
0
19
29
==Test6==
[2 3 4]
[[7 2 3]
 [4 5 6]]
9
8
==Test7==
[0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
