In [8]:
import numpy as np
import pandas as pd

In [6]:
users = ['u1','u2','u3','u4','u5','u6']
print(users)

['u1', 'u2', 'u3', 'u4', 'u5', 'u6']


In [9]:
rating_matrix = np.array(
    [[4,3,0,0,5,0],
     [5,0,4,0,4,0],
     [4,0,5,3,4,0],
     [0,3,0,0,0,5],
     [0,4,0,0,0,4],
     [0,0,2,4,0,5]
    ]
)

In [10]:
rating_matrix.shape

(6, 6)

In [11]:
rating_matrix.dtype

dtype('int32')

In [12]:
rating_matrix[0,:]

array([4, 3, 0, 0, 5, 0])

In [13]:
rating_matrix[:,0]

array([4, 5, 4, 0, 0, 0])

In [18]:
rating_matrix[:,0:2]

array([[4, 3],
       [5, 0],
       [4, 0],
       [0, 3],
       [0, 4],
       [0, 0]])

In [14]:
rating_matrix[2,2]

5

In [20]:
dist = np.sqrt(np.sum(np.square(rating_matrix[0,:]-rating_matrix[1,:])))

In [21]:
dist

5.196152422706632

In [16]:
rating_matrix[0,:]- rating_matrix[1,:]

array([-1,  3, -4,  0,  1,  0])

In [17]:
np.square(rating_matrix[0,:]-rating_matrix[1,:])

array([ 1,  9, 16,  0,  1,  0], dtype=int32)

In [18]:
np.sum(np.square(rating_matrix[0,:]-rating_matrix[1,:]))

27

In [19]:
np.sqrt(np.sum(np.square(rating_matrix[0,:]-rating_matrix[1,:])))

5.196152422706632

In [29]:
dist = np.zeros_like(rating_matrix)

for i in range(rating_matrix.shape[0]):
    for j in range(rating_matrix.shape[0]):
        dist[i,j] = np.sqrt(np.sum(np.square(rating_matrix[i,:]-rating_matrix[j,:])))

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [30]:
dist

array([[ 0,  5,  6,  8,  7,  9],
       [ 5,  0,  3,  9,  9,  9],
       [ 6,  3,  0, 10,  9,  8],
       [ 8,  9, 10,  0,  1,  5],
       [ 7,  9,  9,  1,  0,  6],
       [ 9,  9,  8,  5,  6,  0]])

In [31]:
from sklearn.metrics.pairwise import euclidean_distances

In [32]:
dist = euclidean_distances(rating_matrix)

In [33]:
dist

array([[ 0.        ,  5.19615242,  6.63324958,  8.1240384 ,  7.61577311,
         9.74679434],
       [ 5.19615242,  0.        ,  3.31662479,  9.53939201,  9.43398113,
         9.2736185 ],
       [ 6.63324958,  3.31662479,  0.        , 10.        ,  9.89949494,
         8.18535277],
       [ 8.1240384 ,  9.53939201, 10.        ,  0.        ,  1.41421356,
         5.38516481],
       [ 7.61577311,  9.43398113,  9.89949494,  1.41421356,  0.        ,
         6.08276253],
       [ 9.74679434,  9.2736185 ,  8.18535277,  5.38516481,  6.08276253,
         0.        ]])

In [39]:
def mod(vec):
    return np.sum(vec ** 2) ** 0.5

In [40]:
rating_matrix[0]

array([4, 3, 0, 0, 5, 0])

In [41]:
rating_matrix[0] ** 3

array([ 64,  27,   0,   0, 125,   0], dtype=int32)

In [42]:
def sim(vec1,vec2):
    return np.dot(vec1,vec2) / mod(vec1) / mod(vec2)

In [43]:
sim(rating_matrix[0],rating_matrix[1])

0.7492686492653551

In [44]:
from sklearn.metrics.pairwise import cosine_similarity
sim = cosine_similarity(rating_matrix)
sim

array([[1.        , 0.74926865, 0.62667956, 0.21828206, 0.3       ,
        0.        ],
       [0.74926865, 1.        , 0.91301651, 0.        , 0.        ,
        0.1579597 ],
       [0.62667956, 0.91301651, 1.        , 0.        , 0.        ,
        0.40368671],
       [0.21828206, 0.        , 0.        , 1.        , 0.9701425 ,
        0.63913749],
       [0.3       , 0.        , 0.        , 0.9701425 , 1.        ,
        0.52704628],
       [0.        , 0.1579597 , 0.40368671, 0.63913749, 0.52704628,
        1.        ]])