In [7]:
import numpy as np
A=np.random.rand(4,4)
A

array([[ 0.89938962,  0.39218973,  0.58267035,  0.22136082],
       [ 0.01890629,  0.21945898,  0.03003949,  0.63613657],
       [ 0.97844322,  0.88715602,  0.24074116,  0.95576599],
       [ 0.20456161,  0.815939  ,  0.39301219,  0.31837584]])

In [9]:
B = np.mat(np.random.rand(4,4))
B

matrix([[ 0.98809547,  0.24022385,  0.49252708,  0.28708779],
        [ 0.63045077,  0.51249812,  0.918488  ,  0.00320737],
        [ 0.07125087,  0.93618907,  0.02997519,  0.01218539],
        [ 0.02354402,  0.67541358,  0.53529982,  0.30954303]])

In [10]:
B=np.mat('1 2 3; 4 5 6; 7 8 9')

In [11]:
B

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [13]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [15]:
np.diag([1,2,3,0,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5]])

### 用AA^T创建对称阵

In [16]:
A = np.mat('1 2 3; 4 5 6; 7 8 9')
A * A.T

matrix([[ 14,  32,  50],
        [ 32,  77, 122],
        [ 50, 122, 194]])

### 矩阵基本运算

In [32]:
A = np.mat('1 2 3; 4 5 6; 7 8 9')
B = np.mat(' 4 5 6; 7 8 9; 10 11 12')

In [26]:
print(A)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [27]:
A+B

matrix([[ 5,  7,  9],
        [11, 13, 15],
        [17, 19, 21]])

In [28]:
B = np.mat('4 4 5 6;4 7 8 9;4 10 11 12')
B

matrix([[ 4,  4,  5,  6],
        [ 4,  7,  8,  9],
        [ 4, 10, 11, 12]])

In [29]:
A+B

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

In [33]:
A * B

matrix([[ 48,  54,  60],
        [111, 126, 141],
        [174, 198, 222]])

In [34]:
B * A

matrix([[ 66,  81,  96],
        [102, 126, 150],
        [138, 171, 204]])

In [35]:
A * 10

matrix([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])

In [87]:
c = np.mat(np.random.rand(4,4))

In [89]:
d = c.I

In [90]:
c*d

matrix([[  1.00000000e+00,   2.22044605e-16,   9.19403442e-17,
          -3.05311332e-16],
        [ -1.24900090e-16,   1.00000000e+00,   1.40512602e-16,
           1.11022302e-16],
        [  0.00000000e+00,   2.22044605e-16,   1.00000000e+00,
          -2.22044605e-16],
        [  0.00000000e+00,   1.11022302e-16,  -1.38777878e-17,
           1.00000000e+00]])

In [91]:
d * c

matrix([[  1.00000000e+00,   3.33066907e-16,   4.44089210e-16,
           6.66133815e-16],
        [  0.00000000e+00,   1.00000000e+00,  -1.11022302e-16,
          -2.22044605e-16],
        [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00,
           0.00000000e+00],
        [ -2.22044605e-16,   0.00000000e+00,  -2.22044605e-16,
           1.00000000e+00]])

In [92]:
A

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [93]:
np.linalg.matrix_rank(A)

2

In [94]:
np.linalg.det(A)

-9.5161973539299405e-16

In [95]:
A.I

matrix([[  3.15251974e+15,  -6.30503948e+15,   3.15251974e+15],
        [ -6.30503948e+15,   1.26100790e+16,  -6.30503948e+15],
        [  3.15251974e+15,  -6.30503948e+15,   3.15251974e+15]])

In [96]:
d = A.I

In [97]:
A*d

matrix([[ 0. ,  1. , -0.5],
        [ 0. ,  2. , -1. ],
        [ 0. ,  3. ,  2.5]])

In [98]:
d * A

matrix([[ 12. ,  16. ,  12. ],
        [-10. , -16. , -14. ],
        [  1.5,   4. ,   2.5]])