#### 9.6 改試試迴歸 (Regression) 範例

In [1]:
import numpy as np
from tensorflow.keras.datasets import boston_housing
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.layers import BatchNormalization 

#### 9.6.1 載入資料集

In [2]:
(X_train, y_train), (X_test, y_test) = boston_housing.load_data()

65536/57026 [==================================] - 0s 0us/step


In [3]:
X_train.shape

(404, 13)

In [4]:
X_test.shape

(102, 13)

In [5]:
X_train[0]

array([  1.23247,   0.     ,   8.14   ,   0.     ,   0.538  ,   6.142  ,
        91.7    ,   3.9769 ,   4.     , 307.     ,  21.     , 396.9    ,
        18.72   ])

In [6]:
y_train[0]

15.2

#### 9.6.2 神經網路的架構

In [7]:
model = Sequential()

model.add(Dense(32, input_dim=13, activation='relu'))
model.add(BatchNormalization())

model.add(Dense(16, activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.2))

model.add(Dense(1, activation='linear'))

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 32)                448       
_________________________________________________________________
batch_normalization (BatchNo (None, 32)                128       
_________________________________________________________________
dense_1 (Dense)              (None, 16)                528       
_________________________________________________________________
batch_normalization_1 (Batch (None, 16)                64        
_________________________________________________________________
dropout (Dropout)            (None, 16)                0         
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 17        
Total params: 1,185
Trainable params: 1,089
Non-trainable params: 96
_____________________________________________________

#### 9.6.3 編譯、訓練模型

In [8]:
model.compile(loss='mean_squared_error', optimizer='adam')

In [11]:
#註：由於神經網路的初始權重參數是隨機設定的, 參雜了隨機性, 因此底下 (或您重跑一次) 的結果不會與書中完全一樣, 但模型的能力是相近的
model.fit(X_train, y_train, 
          batch_size=8, epochs=32, verbose=1, 
          validation_data=(X_test, y_test))

Epoch 1/32
51/51 [==============================] - 0s 3ms/step - loss: 47.7289 - val_loss: 54.4794
Epoch 2/32
51/51 [==============================] - 0s 2ms/step - loss: 41.8294 - val_loss: 27.3211
Epoch 3/32
51/51 [==============================] - 0s 2ms/step - loss: 43.4715 - val_loss: 29.7052
Epoch 4/32
51/51 [==============================] - 0s 2ms/step - loss: 44.9643 - val_loss: 58.0492
Epoch 5/32
51/51 [==============================] - 0s 2ms/step - loss: 44.8526 - val_loss: 24.2941
Epoch 6/32
51/51 [==============================] - 0s 2ms/step - loss: 47.5056 - val_loss: 29.8707
Epoch 7/32
51/51 [==============================] - 0s 2ms/step - loss: 38.5279 - val_loss: 40.4831
Epoch 8/32
51/51 [==============================] - 0s 2ms/step - loss: 37.8144 - val_loss: 39.1249
Epoch 9/32
51/51 [==============================] - 0s 2ms/step - loss: 38.6014 - val_loss: 36.7240
Epoch 10/32
51/51 [==============================] - 0s 2ms/step - loss: 44.4404 - val_loss: 37.2530

####9.6.4 實際進行預測

In [ ]:
X_test[42]

array([  9.32909,   0.     ,  18.1    ,   0.     ,   0.713  ,   6.185  ,
        98.7    ,   2.2616 ,  24.     , 666.     ,  20.2    , 396.9    ,
        18.13   ])

In [ ]:
y_test[42]

14.1

In [ ]:
model.predict(np.reshape(X_test[42], [1, 13]))

array([[24.17145]], dtype=float32)