In [1]:
import numpy as np

In [2]:
a = np.arange(16)
print(a)
b = a.reshape((4, 4))
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
