In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
b = a.ravel()
print(b)
b = np.ravel(a)
print(b)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [3]:
b = np.array([[1,2],[3,4],[5,6]])
print(b)
c = b.T
print(c)
c = b.transpose()
print(c)

[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]
[[1 3 5]
 [2 4 6]]


In [4]:
a = np.array([1,2,3])
print(a)
b = a[:, np.newaxis]
print(b)
print(b.shape)

[1 2 3]
[[1]
 [2]
 [3]]
(3, 1)


In [5]:
b = a[np.newaxis, :]
print(b)
print(b.shape)

[[1 2 3]]
(1, 3)


In [6]:
b = a.copy()
print(b)

[1 2 3]


In [7]:
b.fill(4)
print(b)

[4 4 4]


In [8]:
c = np.concatenate((a,b))
print(c)

[1 2 3 4 4 4]


In [9]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
c = np.concatenate((a,b), axis=0)
print(c)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [10]:
c = np.concatenate((a,b), axis=1)
print(c)

[[1 2 5 6]
 [3 4 7 8]]
