In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(a)
b = a[[1, 3, 5, 7]]
print(b)

[1 2 3 4 5 6 7 8 9]
[2 4 6 8]


In [3]:
b = a[range(6)]
print(b)

[1 2 3 4 5 6]


In [4]:
a[[2, 6]] = 10
print(a)

[ 1  2 10  4  5  6 10  8  9]


In [5]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)
c = b[[0,1,2],[0,1,0]]
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 7]


In [6]:
c = np.array([b[0,0],b[1,1],b[2,0]])
print(c)

[1 5 7]


In [7]:
b = np.array([1, 2, 3, 4, 5, 6])
mask = (b % 2 == 0)
print(mask)

[False  True False  True False  True]


In [8]:
a = b[mask]
print(a)
b[b % 2 == 0] = -1
print(b)

[2 4 6]
[ 1 -1  3 -1  5 -1]


In [9]:
b = np.array([[1,2],[3,4],[5,6]])
print(b)
mask = (b > 2)
print(mask)
a = b[mask]
print(b)

[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]
[[1 2]
 [3 4]
 [5 6]]
