In [1]:
import numpy as np

In [2]:
a = np.random.rand(5)
print(a)
b = np.random.rand(3, 2)  
print(b)

[0.14545976 0.57230759 0.23002384 0.54833883 0.38979674]
[[0.80173795 0.55625386]
 [0.18319966 0.70026391]
 [0.81945248 0.2524798 ]]


In [3]:
c = np.random.randint(5, 10, size=5)
print(c)
d = np.random.randint(5, 10, size=(2,3))
print(d)

[5 5 9 7 8]
[[7 5 8]
 [7 5 5]]
