In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4, 5])
print(type(a))
print(a[0], a[1], a[2], a[3], a[4])

<class 'numpy.ndarray'>
1 2 3 4 5


In [3]:
a[0] = 5
print(a)
a[3] = 0
print(a)

[5 2 3 4 5]
[5 2 3 0 5]


In [4]:
b = np.array([[1,2,3],[4,5,6]])
print(b[0, 0], b[0, 1], b[0, 2])
print(b[1, 0], b[1, 1], b[1, 2])

1 2 3
4 5 6


In [5]:
b[0, 0] = 6
b[1, 2] = 1
print(b)

[[6 2 3]
 [4 5 1]]


In [6]:
c = np.array([1, 2, 3, 4, 5], int)
print(c)
d = np.array((1, 2, 3, 4, 5), dtype=float)
print(d)

[1 2 3 4 5]
[1. 2. 3. 4. 5.]
