In [1]:
import numpy as np

In [2]:
a = np.arange(5)
print(a)
b = np.arange(1, 6, 2)
print(b)

[0 1 2 3 4]
[1 3 5]


In [3]:
c = np.zeros(2) 
print(c)  
d = np.zeros((2,2)) 
print(d)

[0. 0.]
[[0. 0.]
 [0. 0.]]


In [4]:
e = np.ones(2) 
print(e)   
f = np.ones((2,2)) 
print(f)

[1. 1.]
[[1. 1.]
 [1. 1.]]


In [5]:
g = np.full(2, 8)
print(g)      
h = np.full((2,2), 7)
print(h)

[8 8]
[[7 7]
 [7 7]]


In [6]:
i = np.array([[1,2,3],[4,5,6]])
j = np.zeros_like(i)
print(j)
k = np.ones_like(i)
print(k)

[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]


In [7]:
l = np.eye(3)  
print(l)
m = np.eye(3, k=1)
print(m)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
