In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
s = 5 
print(s)

[[1 2 3]
 [4 5 6]]
5


In [3]:
c = a + s       
print(c)    
c = a - s       
print(c)   
c = a * s       
print(c)  
c = a / s       
print(c)

[[ 6  7  8]
 [ 9 10 11]]
[[-4 -3 -2]
 [-1  0  1]]
[[ 5 10 15]
 [20 25 30]]
[[0.2 0.4 0.6]
 [0.8 1.  1.2]]


In [4]:
a = np.array([[1,2],[3,4]])
print(a)
s = np.array([[5,6],[7,8]])
print(s)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [5]:
c = a + s       
print(c)    
c = a - s       
print(c)   
c = a * s       
print(c)  
c = a / s       
print(c)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [6]:
c = a.dot(s)       
print(c)

[[19 22]
 [43 50]]
