In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a)
print("a 形狀: " + str(a.shape))
b = np.array([1,0,1])
print(b)
print("b 形狀: " + str(b.shape))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
a 形狀: (4, 3)
[1 0 1]
b 形狀: (3,)


In [3]:
c = a + b
print(c)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
