In [1]:
import numpy as np

In [2]:
a = np.arange(11,36)
a = a.reshape(5,5)
print(a)

[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]


In [3]:
b = a[0, 1:4]
print(b)

[12 13 14]


In [4]:
b = a[1:4, 0]
print(b)

[16 21 26]


In [5]:
b = a[:2, 1:3]
print(b)

[[12 13]
 [17 18]]


In [6]:
b = a[:,1]
print(b)

[12 17 22 27 32]


In [7]:
b = a[::2, ::2]
print(b)

[[11 13 15]
 [21 23 25]
 [31 33 35]]
