In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3]) 
print(a)
s = 5 
print(s)

[1 2 3]
5


In [3]:
c = a + s       
print(c)
c = a - s       
print(c)
c = a * s       
print(c)
c = a / s       
print(c)

[6 7 8]
[-4 -3 -2]
[ 5 10 15]
[0.2 0.4 0.6]


In [4]:
c = np.add(a, s)
print(c)

[6 7 8]


In [5]:
s = np.array([4, 5, 6])
print(s)
c = a + s       
print(c)
c = a - s       
print(c)
c = a * s       
print(c)
c = a / s       
print(c)

[4 5 6]
[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [6]:
c = a.dot(s)       
print(c)

32
