### 2.1　加法與減法

In [1]:
import numpy as np
A = np.matrix([[50, 40],[10, 10]])      # 矩陣A（早上）
B = np.matrix([[30, 100], [20, 15]])    # 矩陣B（晚上）
A+B

matrix([[ 80, 140],
        [ 30,  25]])

### 2.2　矩陣的實數倍

In [2]:
A = np.matrix([[80, 140], [30, 25]])  # 矩陣A
0.8 * A   # 0.8×A

matrix([[ 64., 112.],
        [ 24.,  20.]])

### 2.3　乘法

In [3]:
A = np.matrix([[1, 3], [2, 1]])          # 矩陣A（被乘數）
B = np.matrix([[150, 250], [130, 230]])  # 矩陣B（乘數）
A * B

matrix([[540, 940],
        [430, 730]])

### 2.4　乘法的規則

In [4]:
A = np.matrix([[1, 3], [2, 1]])  # 矩陣A（2×2矩陣）
B = np.matrix([[145], [72]])     # 矩陣B（2×1矩陣）
A * B

matrix([[361],
        [362]])

### 2.5　單位矩陣

In [5]:
A = np.matrix([[1, 3], [2, 1]])  # 矩陣A
E = np.matrix([[1, 0], [0, 1]])  # 單位矩陣E
A * E

matrix([[1, 3],
        [2, 1]])

In [6]:
E * A

matrix([[1, 3],
        [2, 1]])

### 2.6　反矩陣

In [7]:
A = np.matrix([[5, 3], [2, 1]])  # 矩陣A
B = np.linalg.inv(A)             # 計算反矩陣（B）
B

matrix([[-1.,  3.],
        [ 2., -5.]])

In [8]:
(A * B).astype(np.int64)

matrix([[1, 0],
        [0, 1]], dtype=int64)

### 2.7　反矩陣與聯立方程式

In [9]:
A = np.matrix([[5, 3], [2, 1]])  # 矩陣A（未知數係數的矩陣）
inv_A = np.linalg.inv(A)   # 矩陣A的反矩陣
B = np.matrix([[9], [4]])  # 矩陣B（聯立方程式的右邊）
inv_A * B  # 反矩陣×矩陣B

matrix([[ 3.],
        [-2.]])

In [10]:
a = 5  # 矩陣A（未知數係數）
b = 3
c = 2
d = 1
s = 9  # 矩陣B（聯立方程式的右邊）
t = 4
k = a*d - b*c  # 反矩陣的各元素的分母
x = ((d/k)*s) + ((-b/k)*t)  # 反矩陣×矩陣B
y = ((-c/k)*s) + ((a/k*t))
x, y

(3.0, -2.0)