### 1.3　向量的方向

In [1]:
import math
rad = math.atan2(3, 2)  # 計算角度（radian）
th = math.degrees(rad)  # 轉成度數
th

56.309932474020215

### 1.5　向量的運算

In [2]:
import numpy as np
a = np.array([2, 2])  # 向量a的分量
b = np.array([2, -1]) # 向量b的分量

# 加法
a + b

array([4, 1])

In [3]:
# 減法
a - b

array([0, 3])

In [4]:
# 實數倍
>>> 2 * a

array([4, 4])